//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/PauseInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PauseInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PauseInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PauseInputActions"",
    ""maps"": [
        {
            ""name"": ""PauseMap"",
            ""id"": ""7a8ae3d3-20b8-48c8-aa7a-524c4042341d"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""961c3ab7-c2c0-4167-87fd-bb77e5c7d9ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""962ca6dd-b9fc-4a6c-ba18-a7a655a80400"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PauseMap
        m_PauseMap = asset.FindActionMap("PauseMap", throwIfNotFound: true);
        m_PauseMap_Pause = m_PauseMap.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PauseMap
    private readonly InputActionMap m_PauseMap;
    private List<IPauseMapActions> m_PauseMapActionsCallbackInterfaces = new List<IPauseMapActions>();
    private readonly InputAction m_PauseMap_Pause;
    public struct PauseMapActions
    {
        private @PauseInputActions m_Wrapper;
        public PauseMapActions(@PauseInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_PauseMap_Pause;
        public InputActionMap Get() { return m_Wrapper.m_PauseMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseMapActions set) { return set.Get(); }
        public void AddCallbacks(IPauseMapActions instance)
        {
            if (instance == null || m_Wrapper.m_PauseMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PauseMapActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IPauseMapActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IPauseMapActions instance)
        {
            if (m_Wrapper.m_PauseMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPauseMapActions instance)
        {
            foreach (var item in m_Wrapper.m_PauseMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PauseMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PauseMapActions @PauseMap => new PauseMapActions(this);
    public interface IPauseMapActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
